export const incidents = [
  {
    id: 1,
    user: "Alice M.",
    dept: "HR",
    action: "Bulk export: 52,000 customer records",
    time: "2:13 AM",
    date: "2026-06-12",
    risk: "HIGH",
    score: 94,
    anomalyType: "Bulk Export + After Hours",
    flags: ["After-hours access", "Bulk download", "Sensitive data"],
    details: "User downloaded entire customer database in a single session outside business hours. No prior history of such exports.",
    recommendation: "Suspend account immediately, notify manager, initiate DLP review.",
  },
  {
    id: 2,
    user: "Raj K.",
    dept: "Finance",
    action: "Cross-domain: accessed 6 departments in 20 mins",
    time: "11:47 PM",
    date: "2026-06-12",
    risk: "HIGH",
    score: 88,
    anomalyType: "Cross-Department Access",
    flags: ["After-hours access", "Cross-domain access", "Unusual volume"],
    details: "User accessed HR, Legal, IT, Sales, Ops, and Executive folders without any prior cross-department access history.",
    recommendation: "Review access permissions, check for compromised credentials, alert security team.",
  },
  {
    id: 3,
    user: "Carol T.",
    dept: "IT",
    action: "Downloaded all salary data after resignation notice",
    time: "6:02 PM",
    date: "2026-06-12",
    risk: "HIGH",
    score: 85,
    anomalyType: "Exiting Employee Exfiltration",
    flags: ["Exiting employee", "Sensitive data", "Bulk download"],
    details: "Employee submitted resignation 2 days ago. Accessed and downloaded entire payroll and compensation database.",
    recommendation: "Immediately revoke access, preserve forensic evidence, notify HR and legal.",
  },
  {
    id: 4,
    user: "David L.",
    dept: "Sales",
    action: "Accessed restricted competitor pricing DB",
    time: "3:30 AM",
    date: "2026-06-12",
    risk: "HIGH",
    score: 79,
    anomalyType: "Unauthorized Resource Access",
    flags: ["After-hours access", "Unauthorized resource", "Policy violation"],
    details: "User accessed a restricted database normally only available to C-suite. No authorization on record.",
    recommendation: "Block access, escalate to CISO, review audit trail for past 30 days.",
  },
  {
    id: 5,
    user: "Meena S.",
    dept: "Legal",
    action: "Unusual volume: 300+ file opens in 10 mins",
    time: "1:15 AM",
    date: "2026-06-12",
    risk: "MED",
    score: 64,
    anomalyType: "High Velocity Access",
    flags: ["After-hours access", "High velocity"],
    details: "Automated or scripted file access pattern detected. 312 legal documents opened in under 10 minutes.",
    recommendation: "Verify if automated script is authorized, review session logs.",
  },
  {
    id: 6,
    user: "Tom W.",
    dept: "HR",
    action: "Accessed payroll system outside business hours",
    time: "10:55 PM",
    date: "2026-06-12",
    risk: "MED",
    score: 58,
    anomalyType: "After Hours Access",
    flags: ["After-hours access", "Sensitive data"],
    details: "Payroll access at night. User has no on-call duty scheduled. Second occurrence this week.",
    recommendation: "Send automated warning, flag for weekly review.",
  },
  {
    id: 7,
    user: "Priya N.",
    dept: "Ops",
    action: "VPN login from 2 countries within 30 mins",
    time: "8:40 AM",
    date: "2026-06-12",
    risk: "MED",
    score: 51,
    anomalyType: "Impossible Travel",
    flags: ["Impossible travel", "Credential risk"],
    details: "Login from Mumbai at 8:40 AM, then from Frankfurt at 9:08 AM. Physically impossible without credential sharing.",
    recommendation: "Force password reset, enable MFA, investigate credential sharing.",
  },
  {
    id: 8,
    user: "Sam B.",
    dept: "Finance",
    action: "Normal login and report access",
    time: "9:02 AM",
    date: "2026-06-12",
    risk: "LOW",
    score: 12,
    anomalyType: "None",
    flags: [],
    details: "Routine activity within expected parameters.",
    recommendation: "No action required.",
  },
  {
    id: 9,
    user: "Nina R.",
    dept: "Marketing",
    action: "Accessed marketing analytics dashboard",
    time: "10:30 AM",
    date: "2026-06-12",
    risk: "LOW",
    score: 8,
    anomalyType: "None",
    flags: [],
    details: "Normal business hours access to expected resources.",
    recommendation: "No action required.",
  },
];

export const hourlyData = [
  { hour: "0:00", events: 3, anomaly: 0 },
  { hour: "1:00", events: 2, anomaly: 0 },
  { hour: "2:00", events: 0, anomaly: 72 },
  { hour: "3:00", events: 2, anomaly: 0 },
  { hour: "4:00", events: 1, anomaly: 0 },
  { hour: "5:00", events: 3, anomaly: 0 },
  { hour: "6:00", events: 8, anomaly: 0 },
  { hour: "7:00", events: 45, anomaly: 0 },
  { hour: "8:00", events: 80, anomaly: 0 },
  { hour: "9:00", events: 90, anomaly: 0 },
  { hour: "10:00", events: 88, anomaly: 0 },
  { hour: "11:00", events: 92, anomaly: 0 },
  { hour: "12:00", events: 85, anomaly: 0 },
  { hour: "13:00", events: 87, anomaly: 0 },
  { hour: "14:00", events: 90, anomaly: 0 },
  { hour: "15:00", events: 88, anomaly: 0 },
  { hour: "16:00", events: 82, anomaly: 0 },
  { hour: "17:00", events: 75, anomaly: 0 },
  { hour: "18:00", events: 60, anomaly: 0 },
  { hour: "19:00", events: 40, anomaly: 0 },
  { hour: "20:00", events: 25, anomaly: 0 },
  { hour: "21:00", events: 15, anomaly: 0 },
  { hour: "22:00", events: 8, anomaly: 0 },
  { hour: "23:00", events: 5, anomaly: 0 },
];

export const metrics = {
  precision: 78,
  recall: 74,
  f1: 0.76,
  detectionSpeed: "< 3 min",
  explainability: "4/5",
  totalEventsProcessed: "1,247",
  truePositives: 11,
  falsePositives: 3,
  missedThreats: 2,
};

export const complianceMap = [
  { regulation: "GDPR Article 32", status: "Covered", detail: "Unauthorized access monitoring & exfiltration detection" },
  { regulation: "NIST IR-4", status: "Covered", detail: "Incident detection, alerting & response procedures" },
  { regulation: "SOX 302", status: "Covered", detail: "Audit trail for GL, AR, AP financial data access" },
];
